---

- name:  "Check that input variables are well transmitted to launch the role role_jupyterhubV2"
  assert:
    that: "{{ item }} is defined"
  with_items:
    - role_jupyterhub_script_log_dir
    - role_jupyterhub_script_bin_dir
    - role_jupyterhub_script_cfg_dir
    - role_jupyerhub_config_watchdog_mail_alerte
    - role_jupyterhub_script_watchdog
    - role_jupyerhub_script_watchdog_log
    - role_jupyerhub_script_watchdog_error
    - role_jupyterhub_app_user_user
    - role_jupyterhub_app_user_group
    - role_jupyterhub_app_user_user

- name: "Copy exploitation script for Jupyter Hub"
  copy:
    src: "jupyterhub.ksh"
    dest: "{{ role_jupyterhub_script_bin_dir }}/jupyterhub.ksh"
    owner: "{{ role_jupyterhub_app_user_user }}"
    group: "{{ role_jupyterhub_app_user_group }}"

- name: "Add watchdog to auto-restart jupyterhub on fail"
  template:
    src: "templates/ds_appliance_watchdog.sh.j2"
    dest: "{{ role_jupyterhub_script_bin_dir }}/ds_appliance_watchdog.sh"
    owner: "{{ role_jupyterhub_app_user_user }}"
    group: "{{ role_jupyterhub_app_user_group }}"
    mode: "0750"

- name: "Copy config mail alerte for jupyterhub"
  copy:
    src: "files/{{ role_jupyerhub_config_watchdog_mail_alerte }}"
    dest: "{{ role_jupyterhub_script_cfg_dir }}/{{ role_jupyerhub_config_watchdog_mail_alerte }}"
    owner: "{{ role_jupyterhub_app_user_user }}"
    group: "{{ role_jupyterhub_app_user_group }}"
    mode: "0750"

- name: "Create crontab to restart jupyterhub if needed"
  become: "true"
  cron:
    name: "Restart auto jupyterhub"
    user: "{{ role_jupyterhub_app_user_user }}"
    job: "{{ role_jupyterhub_script_bin_dir }}/{{ role_jupyterhub_script_watchdog }} {{ inventory_hostname }}.haas.socgen {{ role_jupyterhub_port }} jupyter 1>{{ role_jupyterhub_script_log_dir }}/{{ role_jupyerhub_script_watchdog_log }} 2>{{ role_jupyterhub_script_log_dir }}/{{ role_jupyerhub_script_watchdog_error }}"


